### ISSUE TITLE
Issue with images in the latest deployments

### ISSUE THREAD

**Issue by zenigma99** [egeldenhuys/ghost-cloudflare-r2#10]
The old deployments still work fine, but in the new ones I'm encountering the following  issue:

The image was successfully uploaded to the R2 storage; however, it is not displaying on the page. This issue may be related to insufficient permissions or an error in the image insertion process . I don't know and I cannot get it why. 
    
I'm using Docker with latest Ghost 5.101.4

**ERROR "POST /ghost/api/admin/images/upload/" 500 2098ms**

```
An unexpected error occurred, please try again.
Error ID:
    dd547f90-adab-11ef-835b-ab280367cc57
Error Code: 
    UNEXPECTED_ERROR
----------------------------------------
Error: Could not determine newPath for image /tmp/61251ef7559150f77ea66c61bb64b19f
    at prepareError (/var/lib/ghost/versions/5.101.4/node_modules/@tryghost/mw-error-handler/lib/mw-error-handler.js:113:19)
    at new GhostError (/var/lib/ghost/versions/5.101.4/node_modules/@tryghost/errors/cjs/GhostError.js:65:23)
    at new InternalServerError (/var/lib/ghost/versions/5.101.4/node_modules/@tryghost/errors/cjs/errors.js:64:5)
    at prepareError (/var/lib/ghost/versions/5.101.4/node_modules/@tryghost/mw-error-handler/lib/mw-error-handler.js:113:19)
    at Layer.handle_error (/var/lib/ghost/versions/5.101.4/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/lib/ghost/versions/5.101.4/node_modules/express/lib/router/index.js:326:13)
    at /var/lib/ghost/versions/5.101.4/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/var/lib/ghost/versions/5.101.4/node_modules/express/lib/router/index.js:346:12)
    at next (/var/lib/ghost/versions/5.101.4/node_modules/express/lib/router/index.js:280:10)
    at versionMismatchHandlerMiddleware (/var/lib/ghost/versions/5.101.4/node_modules/@tryghost/mw-api-version-mismatch/lib/mw-api-version-mismatch.js:27:9)
    at apiVersionCompatibilityErrorHandler (/var/lib/ghost/versions/5.101.4/core/server/services/api-version-compatibility/index.js:29:51)
    at Layer.handle_error (/var/lib/ghost/versions/5.101.4/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/var/lib/ghost/versions/5.101.4/node_modules/express/lib/router/index.js:326:13)
    at /var/lib/ghost/versions/5.101.4/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/var/lib/ghost/versions/5.101.4/node_modules/express/lib/router/index.js:346:12)
    at next (/var/lib/ghost/versions/5.101.4/node_modules/express/lib/router/index.js:280:10)
    at Layer.handle_error (/var/lib/ghost/versions/5.101.4/node_modules/express/lib/router/layer.js:67:12) ```

**Comment by zenigma99** [comment]
It could be that prior to this worked?
    
    `
  urlToPath(url: string) {

    return url.replace(this.domain, '');

  }`

**Comment by zenigma99** [comment]
It can be that prior to this change workes?
    
   
    `  urlToPath(url: string) {

    return url.replace(this.domain, '');

  }`

**Comment by zenigma99** [comment]
Okay, rolling back the R2 adapter to the tag version v0.1.0 works. It has something to do with the changes made In the main branch.
