### ISSUE TITLE
Sharp installation error after upgrading Ghost

### ISSUE THREAD

**Issue by egeldenhuys** [egeldenhuys/ghost-cloudflare-r2#3]
`SHARP_INSTALLATION` error when uploading an image after upgrading from Ghost 5.59.2-alpine to 5.74.0-alpine
ghost-cloudflare-r2 version: 0.1.0

Stack Trace:
```
[2023-11-24 06:42:07] ERROR "POST /ghost/api/admin/images/upload/" 500 515ms
Sharp wasn't installed
Error ID:
    9613ffb0-8a94-11ee-b1da-87d7936028e4
Error Code:
    SHARP_INSTALLATION
----------------------------------------
Error:
    at Object.resizeFromPath (/var/lib/ghost/versions/5.74.0/node_modules/@tryghost/image-transform/lib/transform.js:138:31)
Something went wrong installing the "sharp" module
Error relocating /var/lib/ghost/versions/5.74.0/node_modules/sharp/build/Release/sharp-linuxmusl-x64.node: vips_text_wrap_get_type: symbol not found
Possible solutions:
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current linuxmusl-x64 runtime: "npm install --platform=linuxmusl --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
- Ensure the version of sharp aligns with the sharp package: "npm ls sharp"
    at Object.<anonymous> (/var/lib/ghost/versions/5.74.0/node_modules/sharp/lib/sharp.js:37:9)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/lib/ghost/versions/5.74.0/node_modules/sharp/lib/constructor.js:11:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/var/lib/ghost/versions/5.74.0/node_modules/sharp/lib/index.js:6:15)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
```

Storage adapter config:
```yaml
GHOST_STORAGE_ADAPTER_R2_UUID_NAME: true 
GHOST_STORAGE_ADAPTER_R2_IMAGES_URL_PREFIX: /content/images/ 
GHOST_STORAGE_ADAPTER_R2_MEDIA_URL_PREFIX: /content/media/ 
GHOST_STORAGE_ADAPTER_R2_FILES_URL_PREFIX: /content/files/ 
GHOST_STORAGE_ADAPTER_R2_CONTENT_PREFIX: '' 
GHOST_STORAGE_ADAPTER_R2_GHOST_RESIZE: true 
GHOST_STORAGE_ADAPTER_R2_RESPONSIVE_IMAGES: true 
GHOST_STORAGE_ADAPTER_R2_SAVE_ORIGINAL: false 
# Example widths to get Dawn theme working correctly:
GHOST_STORAGE_ADAPTER_R2_RESIZE_WIDTHS: 300,600,1000,1600,400,750,960,1140,1200 
GHOST_STORAGE_ADAPTER_R2_RESIZE_JPEG_QUALITY: 80 
GHOST_STORAGE_ADAPTER_R2_LOG_LEVEL: debug 
GHOST_STORAGE_ADAPTER_R2_SAVE_ORIG_NAME_METADATA: true 
```

**Comment by Satish-Prajapati** [comment]
Hey @egeldenhuys 
I'm facing the same issue. I've tried multiple workarounds, but nothing has worked so far.
Have you been able to find any solution or workaround for this issue?
Thanks!
